[workspace]

[package]
name = "rustdv-mcp-debug-example"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rustdv = { git = "https://github.com/teabone113/rustdv.git", rev = "259490f6aa659c6016795296d3740def24fdfce3", package = "rustdv" }
rustdv-mcp = { path = "../../mcp" }

[dev-dependencies]
rustdv-vpi-stubs = { git = "https://github.com/teabone113/rustdv.git", rev = "259490f6aa659c6016795296d3740def24fdfce3", package = "rustdv-vpi-stubs" }
